name: segarbox_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  lottie: ^1.4.3
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  flutter_staggered_grid_view: ^0.6.2
  palette_generator: ^0.3.3+2
  flutter_lorem: ^2.0.0
  photo_view: ^0.14.0
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  geocoding: ^2.0.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/image/



